---

- name: configure servers
  hosts: web
  become: true
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: wait 600 seconds for target connection to become reachable/usable
      pause:
        seconds: 600

    - name: install python for Ansible
      apt:
        pkg:
          - python3.8-dev
          - python3.8-distutils
      tags:
        - install
        - install:system-requirements

  roles:
    configure-server