- name: deploy_backend
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
    TYPEORM_HOST: "{{ db_host }}"
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: "{{ db_user_name }}"
    TYPEORM_PASSWORD: "{{ db_password }}"
    TYPEORM_DATABASE: "{{ db_name }}"
