- name: print directory info
  shell: |
    pwd
    ls -a

#- name: Copy index test page
#  template:
#    src: "dist"
#    dest: "~/web/"

#- name: Copy index test page
#  command: cp -r /dist/. ~/web/

#- name: Copy index test page
#  copy:
#    src: /tmp/workspace/backend/dist/
#    dest: ~/web/

#- name: copy consul_ui files
#  command: cp -r {{ item }} ~/web/
#  with_items:
#   - "/tmp/workspace/backend/dist/"

- name: copy backend app
  synchronize:
    src: /tmp/workspace/backend/
    dest: ~/web/

- name: install dependencies
  shell: |
    cd /home/ubuntu/web/
    npm i

- name: Executing node
  shell: |
    cd /home/ubuntu/web/
    pm2 start npm -- start
