- name: print directory info
  shell: |
    pwd
    ls -a

#- name: Copy index test page
#  template:
#    src: "dist"
#    dest: "~/web/"

#- name: Copy index test page
#  command: cp -r /dist/. ~/web/

- name: install rsync on the ansible controller
  connection: local
  package:
    name: rsync
    state: present

- name: Copy index test page
  synchronize:
    src: dist/
    dest: ~/web/

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f